import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { client } from '../lib/sanity'
import Link from 'next/link'

const postsQuery = `*[_type == 'post'] {
  _id,
  _createdAt,
  author,
  title,
  description
} `

export default function Home({posts}) {
  console.log('posts: ', posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {' '}
        hello
        <ul>
          {posts?.length > 0 && posts.map(post => (

            <li key={post._id}>
            <Link href="">
            <a>
            <h1>{post.title}</h1>
            <span>first published at: {post._createAt}</span>
            <p>{post.description}</p>
            </a>
            </Link>
          </li>
            ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const posts = await client.fetch(postsQuery)
  console.log('posts: ', posts)
  return {
    props: { posts },
  }
}
