import Head from 'next/head'
import BlogCard from '../components/BlogCard'
import { client } from '../lib/sanity'

const postsQuery = `*[_type == 'post'] {
  _id,
  slug,
  publishedAt,
  author->{name},
  title,
  description,
  mainImage,
  categories
} `

// TODO: search by categories
const postsCategory = {
  Technology: 'a64a228c-5f07-44b9-8786-95ad54230a43',
  General: 'e9d655f6-d70b-4fcb-94e1-4cf73103bc98',
  Pets: '7022a872-d743-4ca8-8b09-551a56881edb',
  Heroes: '91acf961-fe4c-4c4d-899e-7a967b0768e4',
}
// *[_type == 'post' && references("a64a228c-5f07-44b9-8786-95ad54230a43")]
const postsCategoryQuery = async () => {
  const query = `*[_type == 'post' && references("a64a228c-5f07-44b9-8786-95ad54230a43")]
`
  const CategoryData = await client.fetch(query)
  console.log('CategoryData: ', CategoryData);
}

console.log('postsCategoryQuery: ', postsCategoryQuery);
export default function Home({ posts }) {

  const handleCategory = (e) => {
    e.preventDefault();
    
  }
  console.log('posts: ', posts)
  return (
    <>
      <Head>
        <title>Blog!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

<main>
  <section>
    {Object.keys(postsCategory).map((category, idx) => (
      <li onClick={handleCategory} className='list-none rounded-full px-2 py-1 bg-slate-500 inline-block space-x-4 ml-4 mb-8 cursor-pointer' key={idx}>{category}</li> 
    ))}
  </section>

      <section className='px-2 '>
        <ul className='sm:px-8 gap-4 flfex flex-fcol sm:grid sm:grid-cols-2'>
          {posts?.length > 0 &&
            posts.map((post) => <BlogCard key={post._id} post={post} />)}
        </ul>
      </section>
            </main>
    </>
  )
}

export const getStaticProps = async () => {
  const posts = await client.fetch(postsQuery)
  console.log('posts: ', posts)
  return {
    props: { posts },
  }
}
